### ISSUE TITLE
Investigate how to achieve parallelism in KFServing python model server

### ISSUE THREAD

**Issue by yuzliu** [kubeflow/kfserving#1074]
/kind feature

As the KFServing WG is implementing the load/unload endpoints in the SKLearn and XGBoost model servers to support multi-model serving, I'd like to start a conversion about how to achieve parallelism. 
The goals are:
1)The Python model server can do load(IO bound) and prediction(CPU bound) at the same time for SKLearn and XGBoost models
2)The Python model server can run multiple predictions at the same time for SKLearn and XGBoost 

Our may concerns are:
1. Python is designed with the assumption that each computer only has one core, so it placed a GIL(global interpreter lock) which does not allow multiple threads running in parallel
2. The asyncio based concurrency solutions (fastapi and tornado) use multiple coroutines to achieve concurrency but they share the same thread.  If one prediction coroutine takes a long time, the IO coroutine will be blocked. In addition to that, it does not allow multiple predictions running in parallel.

Some work items to go from here:
1. Investigate a way to share memory between processes and use multiple processes in the model server to achieve parallelism
2. Collect data to understand how slow model server can be if we load hundreds to thousands models into it and share the same process.

**Comment by cliveseldon** [comment]
Some initial thoughts from discussing with @adriangonz 

 * For FastAPI in MLServer look at using a framework such as gunicorn above to allow multiple processes, e.g [maybe this stack](https://github.com/tiangolo/uvicorn-gunicorn-fastapi-docker)
 * Look at shared memory for the model Dict but need to investigate which frameworks are thread safe, e.g.
   * [XGBoost](https://github.com/dmlc/xgboost/issues/5339)
 * **If** load/unload requests can be handled by 1 (Gunicorn) worker they can run in parallel to predict tasks and use asyncio.

**Comment by rtrobin** [comment]
> Kube really expects a single process and any child processes spawned ( as in gunicorn ) that OOM will cause the pod to be restarted and not product the correct metrics (e.g 137 exit code).

@stradigi-andres-de-castro hi buddy! Can you explain more about restriction of spawned child processes? I have encountered a similar [issue](https://github.com/kubeflow/kfserving/issues/1142). I use gunicorn sync mode with multi-workers. The docker image can be deployed and run successfully as a normal pod. But if the pod is deployed in kfserving, the service in pod keeps restarting.

Also we have another custom docker image with tenforflow model. The model can't be initialed correctly either. This program also spawns child process. I'm not sure if this defect is related.

**Comment by stradigi-andres-de-castro** [comment]
Sorry @rtrobin that assertion is incorrect, I was wrong. However, the last line on your Docker container - the "CMD" entry is considered the "init", kube will listen to only that process. Gunicorn forks - creates child processes, and now you have a system where kube in unaware of your your child processes and depends entirely on gunicorn to reap them. 

This is why I suggest to keep the integration as simple as possible, ditch multiprocessing in a pod a stick to multiple replicas, you will pay the cost of extra memory consumption because of your models but it prevents serious nagging issues with the design of the system.

**Comment by rtrobin** [comment]
@stradigi-andres-de-castro Thanks for your hint. Now my problem is fixed. Due to the multi-process scheme I use, the pod runs OOM, so that gunicorn keeps restarting child processes.

My new question is: what the default memory setting is in kfserving? I had expected pod deployed in kfserving had no limit restrict if not explicitly indicated. @yuzisun

**Comment by yuzisun** [comment]
> @stradigi-andres-de-castro Thanks for your hint. Now my problem is fixed. Due to the multi-process scheme I use, the pod runs OOM, so that gunicorn keeps restarting child processes.
> 
> My new question is: what the default memory setting is in kfserving? I had expected pod deployed in kfserving had no limit restrict if not explicitly indicated. @yuzisun

@rtrobin the default limit is 2Gi, it is good practice to always specify a memory limit in k8s environment to prevent impacting the other pods on the same node.
