### ISSUE TITLE
[storage-initializer] add support for aws sts

### ISSUE THREAD

**Issue by raffaelespazzoli** [kubeflow/kfserving#1451]
/kind feature

**Describe the solution you'd like**
currently the only understood AWS credentials are the following environment variables:
AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY. 
Another common and more secure method of authenticating a connection in kubernetes is to use STS federation and kube projected token. The approach is described here[1]. All standard aws clients understand this approach based on the well known environment variables so normally one decides which to use by populating certain environment variable and not others.
But because here the client is really a minio client and not a aws s3 client, the sts federation approach is not automatically understood.
The request is to add this capability.

[1]: https://github.com/aws/amazon-eks-pod-identity-webhook 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by iptizer** [comment]
#831  Should solve this.

PR => #1472

**Comment by ReggieCarey** [comment]
How does this decision affect users that do not use AWS infrastructure?  Why are proprietary solutions creeping into an open source project?

**Comment by DavidSpek** [comment]
@ReggieCarey Support doesn't mean you have to use it or that it is the only option to use.

**Comment by rawc0der** [comment]
Hi guys,

I'm soo glad this is fixed, however there seems to be some missing dependencies in order to make this work with the provided upstream components.


I think the docker image `quay.io/aipipeline/kfserving-component` referenced in the Kubeflow Pipelines samples in `component.yaml` file is still not updated to the `0.6 release`.  I can adapt my use-case to run the component image on private repo but I would like to help if possible.

I don't know which `CI` is in charge of docker building, 
@iptizer  , @DavidSpek, is there some other PR, maybe (https://github.com/kubeflow/pipelines/issues/5700) still in need of attention? Can I be of any help to this issue somehow?
