### ISSUE TITLE
How to use GPU in custom kfserving?

### ISSUE THREAD

**Issue by SeibertronSS** [kubeflow/kfserving#1724]
How to use GPU in custom kfserving? Can it be specified directly through `k8s_client.V1ResourceRequirements`? Still need to build a image that contains cuda? Should I use `docker build` or [pack CIL](https://buildpacks.io/docs/tools/pack/)?

**Comment by yuzisun** [comment]
@SeibertronSS the custom image needs to include cuda, can check if there is an existing pack builder which does this for you otherwise you might need to write your own dockerfile to install it, there is an [example](https://github.com/kubeflow/kfserving/blob/master/python/pytorch-gpu.Dockerfile#L23) for pytorch, in future kfserving could also provide a pack builder for you out of the box.

**Comment by SeibertronSS** [comment]
Thank you very much for your suggestions, I will try some experiments.
