### ISSUE TITLE
Install kfserving with kubeflow CLI kfctl

### ISSUE THREAD

**Issue by jinchihe** [kubeflow/kfserving#196]
/kind feature

**Describe the solution you'd like**
Install kfserving with kubeflow.

I'm not sure if here is right place to log this, but want to confirm any plan to install kfsering with kubeflow? as kfserving depends on isito and kantive, seems a bit complicated for installation. Thanks.

/cc @ellis-bigelow

**Comment by ryandawsonuk** [comment]
I recently hit the related case of wanting to install knative on top of kubeflow. That led to the complication that kubeflow master now has istio already. What I did was just re-use the kubeflow install of istio and [install the non-istio knative components on top of that](https://github.com/SeldonIO/seldon-core/pull/650/files#diff-a081dd1cf5f2ab290b9ff95c58a66291R3). I found this works fine. But it did throw up a question about gateways and auth.

The kubeflow gateway is now called `kubeflow-gateway` and that is referenced in all the istio VirtualServices exposed under it. Knative services use the knative default gateway of `knative-ingress-gateway`. When I do `kubectl get gateway --all-namespaces` I see both listed. I don't think that's in conflict though. I presume that if I call the external istio-ingressgateway IP with the right host header then the curl should still hit the correct knative service.

I say that I presume as I am not entirely sure. I've setup [security with the kubeflow install on the istio-ingressgateway](https://github.com/kubeflow/kubeflow/pull/3538). The security works great for accessing the kubeflow services via the kubeflow dashboard UI. But naturally when I do a curl with a host header then I just get an HTML redirect returned that wants to send me to the auth login page.

**Comment by jinchihe** [comment]
@ryandawsonuk Thanks for the information. so seems you have experience to install knative on top of kubeflow. Do you have plan to contribute to kubeflow for this? since the PR is for seldon-core. :-) if so may kfserving can be installed with kubeflow.

**Comment by ryandawsonuk** [comment]
I've submitted a PR to add a note on this https://github.com/kubeflow/kfserving/pull/200

It is perhaps not what you were looking for as the kf-serving docs still just refer to the knative docs. The knative docs are quite complex as they allow for a lot of configuration options. It would be possible to provide a single script but that would mean being more opinionated.

I will try to catch up with @yanniszark about the auth question. I found I can get details of the dex installation through a combination of:
```
curl http://$ISTIO_INGRESS:5556/dex/.well-known/openid-configuration
kubectl get deployment -n kubeflow authservice -o jsonpath='{.spec.template.spec.containers[*].env}'
```
Then I tried to get a token using:
```
curl -X POST -d "client_id=kubeflow-authservice-oidc&client_secret=$CLIENT_SECRET&grant_type=password&username=admin@kubeflow.org&password=12341234" http://$ISTIO_INGRESS:5556/dex/token
```
But dex replies with `{"error":"invalid_grant"}`. So currently if the KF istio endpoint is authenticated then I only know how to curl services from within the cluster rather than going through auth.

**Comment by yanniszark** [comment]
Hi @ryandawsonuk !
Thanks for your interest in our reference implementation of Kubeflow for existing kubernetes clusters, with Istio + Dex for Auth.
I'd love to be able to install KFServing natively with `kfctl`, so I'd like to help towards that goal.

> I will try to catch up with @yanniszark about the auth question. I found I can get details of the dex installation through a combination of:

Dex uses the [OIDC standard](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfig), in which the `/.well-known/openid-configuration` path is reserved for discovery.

> The kubeflow gateway is now called kubeflow-gateway and that is referenced in all the istio VirtualServices exposed under it. Knative services use the knative default gateway of knative-ingress-gateway.

Is the `knative-ingress-gateway` really needed?
We should be able to make it work with the `kubeflow-gateway`.
The KNative VirtualServices just need to be changed to refer to `kubeflow-gateway` instead of `knative-ingress-gateway`.

> But dex replies with {"error":"invalid_grant"}. Perhaps the password flow is disabled. 

AFAIK, Dex doesn't support the password grant type, only the Authorization code and Refresh token grant types. Dex can support multiple auth backends (eg static user file, ldap, external IdP).
More info: https://github.com/dexidp/dex/issues/764

> But naturally when I do a curl with a host header then I just get an HTML redirect returned that wants to send me to the auth login page.

With the current implementation, after logging in, you get a cookie named `auth` which contains the encrypted `id_token` (see OIDC specification).
For authenticating using curl, you can put that cookie inside the `X-Auth-Token` header (also looks for that) and it should work.

**Comment by yuzisun** [comment]
I am pretty sure that `knative-ingress-gateway` is already deprecated have been removed since knative 0.5 release.

**Comment by ryandawsonuk** [comment]
Yeah dex doesn't support password grant type https://github.com/dexidp/dex/issues/764

**Comment by ryandawsonuk** [comment]
@yanniszark FYI I found that in order to use X-Auth-Token I needed to modify the envoy filter - https://github.com/kubeflow/kubeflow/pull/3607/files#diff-1f4e95368adf8910db69d093599a3ce4R22

**Comment by ryandawsonuk** [comment]
It seems the JWT will now be a header and have the name kubeflow-userid - https://github.com/kubeflow/kubeflow/commit/1fa142f8a5c355b5395ec0e91280d32d76eccdce#diff-784a8a186986389ad03cf28aef0b2fe9R55

**Comment by jinchihe** [comment]
@johnugeorge Just confirm here, KFServing will be installed in new version of kubeflow by kfctl along with istio and kantive, right? if so the CI/CD test env will have KFServing provision, right? Thanks a lot!

**Comment by johnugeorge** [comment]
Yes. right.  With the latest Kfctl config in GCP, KF installation deploys KFServing by default with Istio and KNative.
