### ISSUE TITLE
Inference service status always be "False" after restart K8S cluster

### ISSUE THREAD

**Issue by pugangxa** [kubeflow/kfserving#456]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
After restart K8S cluster the inferenceservice status will be "False" forever but in fact it's working.
1: Apply the sample kubeflow/kfserving/docs/samples/tensorflow
2: Everything is fine and the case just worked as in the doc
3: Stop K8S cluster(I use Docker for Mac which just need disable the local cluster)
4: Enabler the cluster local again.
It's always like this:
➜  tensorflow git:(master) ✗ k get inferenceservices.serving.kubeflow.org
NAME             URL   READY   DEFAULT TRAFFIC   CANARY TRAFFIC   AGE
flowers-sample         False                                      46m

But all the knative service/deployments are fine:
➜  tensorflow git:(master) ✗ k get deployments
NAME                                                READY   UP-TO-DATE   AVAILABLE   AGE
flowers-sample-predictor-default-w8pd6-deployment   0/0     0            0           49m
➜  tensorflow git:(master) ✗ k get service.serving.knative.dev
NAME                               URL                                                           LATESTCREATED                            LATESTREADY                              READY     REASON
flowers-sample-predictor-default   http://flowers-sample-predictor-default.default.example.com   flowers-sample-predictor-default-w8pd6   flowers-sample-predictor-default-w8pd6   Unknown   IngressNotConfigured

The predict service in fact is working but the status is not proprgated correctly:
➜  tensorflow git:(master) ✗ curl -v -H "Host: ${SERVICE_HOSTNAME}" http://localhost/v1/models/$MODEL_NAME:predict -d $INPUT_PATH
*   Trying ::1:80...
* TCP_NODELAY set
* Connected to localhost (::1) port 80 (#0)
> POST /v1/models/flowers-sample:predict HTTP/1.1
> Host: flowers-sample.default.example.com
> User-Agent: curl/7.66.0
> Accept: */*
> Content-Length: 16201
> Content-Type: application/x-www-form-urlencoded
> Expect: 100-continue
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 100 Continue
* We are completely uploaded and fine
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< content-length: 222
< content-type: application/json
< date: Thu, 17 Oct 2019 08:56:07 GMT
< x-envoy-upstream-service-time: 36065
< server: istio-envoy
<
{
    "predictions": [
        {
            "scores": [0.999114931, 9.20987877e-05, 0.000136786213, 0.000337257545, 0.000300532585, 1.84813616e-05],
            "prediction": 0,
            "key": "   1"
        }
    ]
* Connection #0 to host localhost left intact
}%

➜  tensorflow git:(master) ✗ k get inferenceservices.serving.kubeflow.org
NAME             URL   READY   DEFAULT TRAFFIC   CANARY TRAFFIC   AGE
flowers-sample         False                                      51m

**What did you expect to happen:**
The inference service status should be correct and the URL shows correctly.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:1.3.2
- Knative Version:0.9.0
- KFServing Version:master
- Kubeflow version:master
- Minikube version:
- Kubernetes version: (use `kubectl version`):

- OS (e.g. from `/etc/os-release`):

**Comment by pugang1985** [comment]
The log shows it's due to call error when ""error":"Internal error occurred: failed calling webhook",

{"level":"error","ts":1571301423.7336009,"logger":"kubebuilder.controller","msg":"Reconciler error","controller":"kfserving-controller","request":"default/flowers-sample","error":"Internal error occurred: failed calling webhook \"inferenceservice.kfserving-webhook-server.defaulter\": Post https://kfserving-webhook-server-service.kfserving-system.svc:443/mutate-inferenceservices?timeout=30s: dial tcp 10.107.3.250:443: connect: connection refused","stacktrace":"github.com/kubeflow/kfserving/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/kubeflow/kfserving/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/kubeflow/kfserving/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/kubeflow/kfserving/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:217\ngithub.com/kubeflow/kfserving/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/src/github.com/kubeflow/kfserving/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\ngithub.com/kubeflow/kfserving/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/src/github.com/kubeflow/kfserving/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/kubeflow/kfserving/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/github.com/kubeflow/kfserving/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/kubeflow/kfserving/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/github.com/kubeflow/kfserving/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}

But in fact the webhook works fine:
➜  tensorflow git:(master) ✗ k get service -n kfserving-system
NAME                                           TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
kfserving-controller-manager-metrics-service   ClusterIP   10.97.231.215   <none>        8443/TCP   26h
kfserving-controller-manager-service           ClusterIP   10.103.7.139    <none>        443/TCP    26h
kfserving-webhook-server-service               ClusterIP   10.107.3.250    <none>        443/TCP    26h

**Comment by pugang1985** [comment]
Should we do below changes to this?

diff --git a/pkg/controller/inferenceservice/controller.go b/pkg/controller/inferenceservice/controller.go
index 6a5a046d..a3a1f3e6 100644
--- a/pkg/controller/inferenceservice/controller.go
+++ b/pkg/controller/inferenceservice/controller.go
@@ -18,6 +18,7 @@ package service

 import (
        "context"
+
        "github.com/kubeflow/kfserving/pkg/controller/inferenceservice/reconcilers/istio"

        "github.com/kubeflow/kfserving/pkg/constants"
@@ -174,7 +175,7 @@ func (r *ReconcileService) updateStatus(desiredService *kfserving.InferenceServi
                // This is important because the copy we loaded from the informer's
                // cache may be stale and we don't want to overwrite a prior update
                // to status with this stale state.
-       } else if err := r.Update(context.TODO(), desiredService); err != nil {
+       } else if err := r.Status().Update(context.TODO(), desiredService); err != nil {
                log.Error(err, "Failed to update InferenceService status")
                r.Recorder.Eventf(desiredService, v1.EventTypeWarning, "UpdateFailed",
                        "Failed to update status for InferenceService %q: %v", desiredService.Name, err)

I will do some test of this.

**Comment by yuzisun** [comment]
closing old issue
