### ISSUE TITLE
pylint pre-submit python 3.5.2

### ISSUE THREAD

**Issue by cliveseldon** [kubeflow/kfserving#813]
/kind bug

The pylint pre-submit is using python 3.5.2 but our python libraries are >= python 3.6

**Comment by jinchihe** [comment]
@cliveseldon That's caused by the `gcr.io/kubeflow-ci/test-worker` is using python 3.5, I recall that we tried to upgrade Python, but caused some problems for other repos. 
Yeah, I agree with you, we should upgrade that. But for now, I suggest to work around that by ignoring that temporary. I will apend the ignoring solution in PR #803

**Comment by cliveseldon** [comment]
Thanks @jinchihe Strange as @jlewi suggested the python version could be set https://kubeflow.slack.com/archives/CHCKRA1N2/p1589133147009900?thread_ts=1588954800.008600&cid=CHCKRA1N2

**Comment by jlewi** [comment]
We have a newer test worker image that should be using python3.8
https://github.com/kubeflow/testing/blob/master/images/Dockerfile.py3

The docker image is
gcr.io/kubeflow-ci/test-worker-py3

Most recent build is:
gcr.io/kubeflow-ci/test-worker-py3@sha256:b679ce5d7edbcc373fd7d28c57454f4f22ae987f200f601252b6dcca1fd8823b

**Comment by jlewi** [comment]
Also kubeflow/testing#425 is tracking adding support for Tekton workflows which should make it easier to define reusable Tekton tasks/pipelines for unittests and lint.

**Comment by jinchihe** [comment]
@jlewi Yeah, will enhance the testing by using Tekton later. Thanks.
