### ISSUE TITLE
[AWS] Support IAM Role for Service Account in KFServing

### ISSUE THREAD

**Issue by Jeffwan** [kubeflow/kfserving#831]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Currently, it needs a S3 credential to download model. We need more fine grain control ways. [IRSA](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html) is a better option. This helps us deploy model without credentials
 
**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by ellistarn** [comment]
Hey @Jeffwan! Great feature. I'm less familiar with the AWS terminology. It looks like this will enable short lived credentials similar to GKE's managed pod identity. 

I just want to confirm that these credentials will go through the Kubernetes Service Account API and that no API change is necessary from a KFServing perspective. What is the difference from an implementation perspective? IIUC, we currently read some AWS environment variables to retrieve the credentials -- what's different with IRSA?

**Comment by Jeffwan** [comment]
>  It looks like this will enable short lived credentials within pods, similar to GKE's managed pod identity.

Exactly. This will be same as workload identity. 

> I just want to confirm that these credentials will go through the Kubernetes Service Account API and that no API change is necessary from a KFServing perspective. What is the difference from an implementation perspective? IIUC, we currently read some AWS environment variables to retrieve the credentials -- what's different with IRSA?

KFServing side doesn't need to make any API level change or even calls. User needs to choose service account with IAM role attached for inference service. EKS has the webhook to inject the temporary token from IAM role into the pod. There's two things need to be done. 

1. Upgrade AWS or Minio SDK to the version that support `assume-web-identity-role` 
2. Add `assume-web-identity-role` in the credential resolver chain and pod will load token to exchange temporary credentials. 

This maybe supported out-of-box in kfserving and I have not checked it yet. I just create the issue for tracking purpose.

**Comment by chris-zen** [comment]
There is something else that it would be nice to have support for, which is to be able to chain into another role, once the web-identity-role has been configured. That's because our data-lake in S3 doesn't support the new web-identity roles yet, and we need to chain (assume roles) from the one configured by the EKS webhook.

`pod-role-with-web-identity ---[assume]---> data-lake-role ===> download model`

**Comment by mttcnnff** [comment]
@Jeffwan I made this PR for using boto instead of minio for the storage initializer, seems related to this issue.
https://github.com/kubeflow/kfserving/pull/1130

**Comment by ReggieCarey** [comment]
Is this a vendor specific proprietary solution creeping into an open source offering?

**Comment by karlschriek** [comment]
@ReggieCarey you seem to have a complete misconception of what open source is. I have seen several of your comments on the issue boards, mainly complaining about not successfully being able to join the Slack community and therefore falsely drawing the conclusion that "Microsoft, Google, and other proprietary orgs, limit who can use the publicly advertised slack channels" and constantly posting that "proprietary solution [are] creeping into an open source offering".

Let me clear it up for you: open source means collaboration between various different organizations and individuals in order to create shared functionality to the benefit of all. That means yes, _absolutely_ yes, Kubeflow should support using functionality that is provided by Google, AWS and so forth if that is what is needed by Kubeflow's user base.
